# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acc_app_optimisation/gui/control_pane.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ControlPane(object):
    def setupUi(self, ControlPane):
        ControlPane.setObjectName("ControlPane")
        ControlPane.resize(310, 599)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ControlPane.sizePolicy().hasHeightForWidth())
        ControlPane.setSizePolicy(sizePolicy)
        ControlPane.setMinimumSize(QtCore.QSize(310, 0))
        self.mainLayout = QtWidgets.QVBoxLayout(ControlPane)
        self.mainLayout.setObjectName("mainLayout")
        self.machineLayout = QtWidgets.QFormLayout()
        self.machineLayout.setObjectName("machineLayout")
        self.machinePaneLabel = QtWidgets.QLabel(ControlPane)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.machinePaneLabel.setFont(font)
        self.machinePaneLabel.setObjectName("machinePaneLabel")
        self.machineLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.machinePaneLabel
        )
        self.machineCombo = QtWidgets.QComboBox(ControlPane)
        self.machineCombo.setMinimumSize(QtCore.QSize(0, 30))
        self.machineCombo.setObjectName("machineCombo")
        self.machineLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.machineCombo
        )
        self.mainLayout.addLayout(self.machineLayout)
        self.lsaSelectorWidget = QtWidgets.QWidget(ControlPane)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lsaSelectorWidget.sizePolicy().hasHeightForWidth()
        )
        self.lsaSelectorWidget.setSizePolicy(sizePolicy)
        self.lsaSelectorWidget.setMinimumSize(QtCore.QSize(100, 200))
        self.lsaSelectorWidget.setObjectName("lsaSelectorWidget")
        self.mainLayout.addWidget(self.lsaSelectorWidget)
        self.settingsTabWidget = QtWidgets.QTabWidget(ControlPane)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.settingsTabWidget.sizePolicy().hasHeightForWidth()
        )
        self.settingsTabWidget.setSizePolicy(sizePolicy)
        self.settingsTabWidget.setObjectName("settingsTabWidget")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.settingsLayout = QtWidgets.QVBoxLayout(self.settingsTab)
        self.settingsLayout.setObjectName("settingsLayout")
        self.environmentLabel = QtWidgets.QLabel(self.settingsTab)
        self.environmentLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.environmentLabel.setFont(font)
        self.environmentLabel.setObjectName("environmentLabel")
        self.settingsLayout.addWidget(self.environmentLabel)
        self.environmentCombo = QtWidgets.QComboBox(self.settingsTab)
        self.environmentCombo.setMinimumSize(QtCore.QSize(0, 40))
        self.environmentCombo.setObjectName("environmentCombo")
        self.settingsLayout.addWidget(self.environmentCombo)
        self.configEnvButton = QtWidgets.QPushButton(self.settingsTab)
        self.configEnvButton.setEnabled(False)
        self.configEnvButton.setObjectName("configEnvButton")
        self.settingsLayout.addWidget(self.configEnvButton)
        self.showConstraintsCheckbox = QtWidgets.QCheckBox(self.settingsTab)
        self.showConstraintsCheckbox.setEnabled(False)
        self.showConstraintsCheckbox.setObjectName("showConstraintsCheckbox")
        self.settingsLayout.addWidget(self.showConstraintsCheckbox)
        self.algoSelectionLabel = QtWidgets.QLabel(self.settingsTab)
        self.algoSelectionLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.algoSelectionLabel.setFont(font)
        self.algoSelectionLabel.setObjectName("algoSelectionLabel")
        self.settingsLayout.addWidget(self.algoSelectionLabel)
        self.algoCombo = QtWidgets.QComboBox(self.settingsTab)
        self.algoCombo.setMinimumSize(QtCore.QSize(0, 40))
        self.algoCombo.setObjectName("algoCombo")
        self.settingsLayout.addWidget(self.algoCombo)
        self.configOptButton = QtWidgets.QPushButton(self.settingsTab)
        self.configOptButton.setObjectName("configOptButton")
        self.settingsLayout.addWidget(self.configOptButton)
        self.line = QtWidgets.QFrame(self.settingsTab)
        self.line.setMinimumSize(QtCore.QSize(0, 30))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.settingsLayout.addWidget(self.line)
        self.runLayout = QtWidgets.QHBoxLayout()
        self.runLayout.setObjectName("runLayout")
        self.launchButton = QtWidgets.QPushButton(self.settingsTab)
        self.launchButton.setObjectName("launchButton")
        self.runLayout.addWidget(self.launchButton)
        self.stopButton = QtWidgets.QPushButton(self.settingsTab)
        self.stopButton.setEnabled(False)
        self.stopButton.setObjectName("stopButton")
        self.runLayout.addWidget(self.stopButton)
        self.resetButton = QtWidgets.QPushButton(self.settingsTab)
        self.resetButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setObjectName("resetButton")
        self.runLayout.addWidget(self.resetButton)
        self.settingsLayout.addLayout(self.runLayout)
        self.settingsTabWidget.addTab(self.settingsTab, "")
        self.mainLayout.addWidget(self.settingsTabWidget)

        self.retranslateUi(ControlPane)
        self.settingsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ControlPane)

    def retranslateUi(self, ControlPane):
        _translate = QtCore.QCoreApplication.translate
        self.machinePaneLabel.setText(_translate("ControlPane", "Machine: "))
        self.environmentLabel.setText(_translate("ControlPane", "Environment:"))
        self.configEnvButton.setText(_translate("ControlPane", "Configure"))
        self.showConstraintsCheckbox.setText(
            _translate("ControlPane", "Show constraints")
        )
        self.algoSelectionLabel.setText(
            _translate("ControlPane", "Numerical optimisation algo: ")
        )
        self.configOptButton.setText(_translate("ControlPane", "Configure"))
        self.launchButton.setText(_translate("ControlPane", "Launch"))
        self.stopButton.setText(_translate("ControlPane", "Stop"))
        self.resetButton.setText(_translate("ControlPane", "Reset"))
        self.settingsTabWidget.setTabText(
            self.settingsTabWidget.indexOf(self.settingsTab),
            _translate("ControlPane", "Config"),
        )
