# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acc_app_optimisation/gui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 708)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlArea = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlArea.sizePolicy().hasHeightForWidth())
        self.controlArea.setSizePolicy(sizePolicy)
        self.controlArea.setMinimumSize(QtCore.QSize(310, 0))
        self.controlArea.setObjectName("controlArea")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controlArea)
        self.verticalLayout.setObjectName("verticalLayout")
        self.machineSelectionPane = QtWidgets.QWidget(self.controlArea)
        self.machineSelectionPane.setMinimumSize(QtCore.QSize(0, 40))
        self.machineSelectionPane.setObjectName("machineSelectionPane")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.machineSelectionPane)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.machinePaneLabel = QtWidgets.QLabel(self.machineSelectionPane)
        self.machinePaneLabel.setObjectName("machinePaneLabel")
        self.horizontalLayout_2.addWidget(self.machinePaneLabel)
        self.machineCombo = QtWidgets.QComboBox(self.machineSelectionPane)
        self.machineCombo.setMinimumSize(QtCore.QSize(0, 30))
        self.machineCombo.setObjectName("machineCombo")
        self.horizontalLayout_2.addWidget(self.machineCombo)
        self.verticalLayout.addWidget(self.machineSelectionPane)
        self.controlPane = QtWidgets.QWidget(self.controlArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlPane.sizePolicy().hasHeightForWidth())
        self.controlPane.setSizePolicy(sizePolicy)
        self.controlPane.setMinimumSize(QtCore.QSize(0, 200))
        self.controlPane.setMaximumSize(QtCore.QSize(16777215, 200))
        self.controlPane.setObjectName("controlPane")
        self.verticalLayout.addWidget(self.controlPane)
        self.setting_tab_widget = QtWidgets.QTabWidget(self.controlArea)
        self.setting_tab_widget.setMinimumSize(QtCore.QSize(0, 370))
        self.setting_tab_widget.setObjectName("setting_tab_widget")
        self.setting_tab = QtWidgets.QWidget()
        self.setting_tab.setObjectName("setting_tab")
        self.settingPane = QtWidgets.QWidget(self.setting_tab)
        self.settingPane.setGeometry(QtCore.QRect(11, 10, 270, 321))
        self.settingPane.setObjectName("settingPane")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settingPane)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.environmentLabel = QtWidgets.QLabel(self.settingPane)
        self.environmentLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.environmentLabel.setObjectName("environmentLabel")
        self.verticalLayout_2.addWidget(self.environmentLabel)
        self.environmentCombo = QtWidgets.QComboBox(self.settingPane)
        self.environmentCombo.setMinimumSize(QtCore.QSize(0, 40))
        self.environmentCombo.setObjectName("environmentCombo")
        self.verticalLayout_2.addWidget(self.environmentCombo)
        self.configEnvButton = QtWidgets.QPushButton(self.settingPane)
        self.configEnvButton.setObjectName("configEnvButton")
        self.verticalLayout_2.addWidget(self.configEnvButton)
        self.algoSelectionLabel = QtWidgets.QLabel(self.settingPane)
        self.algoSelectionLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.algoSelectionLabel.setObjectName("algoSelectionLabel")
        self.verticalLayout_2.addWidget(self.algoSelectionLabel)
        self.algoCombo = QtWidgets.QComboBox(self.settingPane)
        self.algoCombo.setMinimumSize(QtCore.QSize(0, 40))
        self.algoCombo.setObjectName("algoCombo")
        self.verticalLayout_2.addWidget(self.algoCombo)
        self.configOptButton = QtWidgets.QPushButton(self.settingPane)
        self.configOptButton.setObjectName("configOptButton")
        self.verticalLayout_2.addWidget(self.configOptButton)
        self.line = QtWidgets.QFrame(self.settingPane)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.buttonPane = QtWidgets.QWidget(self.settingPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPane.sizePolicy().hasHeightForWidth())
        self.buttonPane.setSizePolicy(sizePolicy)
        self.buttonPane.setMinimumSize(QtCore.QSize(230, 50))
        self.buttonPane.setObjectName("buttonPane")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.buttonPane)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.launchButton = QtWidgets.QPushButton(self.buttonPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.launchButton.sizePolicy().hasHeightForWidth())
        self.launchButton.setSizePolicy(sizePolicy)
        self.launchButton.setMinimumSize(QtCore.QSize(75, 0))
        self.launchButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.launchButton.setObjectName("launchButton")
        self.horizontalLayout_3.addWidget(self.launchButton)
        self.stopButton = QtWidgets.QPushButton(self.buttonPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(75, 0))
        self.stopButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_3.addWidget(self.stopButton)
        self.resetButton = QtWidgets.QPushButton(self.buttonPane)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_3.addWidget(self.resetButton)
        self.verticalLayout_2.addWidget(self.buttonPane)
        self.setting_tab_widget.addTab(self.setting_tab, "")
        self.correction_tab = QtWidgets.QWidget()
        self.correction_tab.setObjectName("correction_tab")
        self.correctionScrollArea = QtWidgets.QScrollArea(self.correction_tab)
        self.correctionScrollArea.setGeometry(QtCore.QRect(10, 10, 120, 80))
        self.correctionScrollArea.setWidgetResizable(True)
        self.correctionScrollArea.setObjectName("correctionScrollArea")
        self.correctionScrollPane = QtWidgets.QWidget()
        self.correctionScrollPane.setGeometry(QtCore.QRect(0, 0, 118, 78))
        self.correctionScrollPane.setObjectName("correctionScrollPane")
        self.correctionScrollArea.setWidget(self.correctionScrollPane)
        self.setting_tab_widget.addTab(self.correction_tab, "")
        self.verticalLayout.addWidget(self.setting_tab_widget)
        self.horizontalLayout.addWidget(self.controlArea)
        self.plotTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.plotTabWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.plotTabWidget.setObjectName("plotTabWidget")
        self.plotPane = QtWidgets.QWidget()
        self.plotPane.setAccessibleName("")
        self.plotPane.setObjectName("plotPane")
        self.plotTabWidget.addTab(self.plotPane, "")
        self.networkfityPane = QtWidgets.QWidget()
        self.networkfityPane.setObjectName("networkfityPane")
        self.plotTabWidget.addTab(self.networkfityPane, "")
        self.horizontalLayout.addWidget(self.plotTabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.setting_tab_widget.setCurrentIndex(0)
        self.plotTabWidget.setCurrentIndex(0)
        self.actionClose.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "acc optimisation"))
        self.machinePaneLabel.setText(_translate("MainWindow", "Machine: "))
        self.environmentLabel.setText(_translate("MainWindow", "Environment:"))
        self.configEnvButton.setText(_translate("MainWindow", "Configure"))
        self.algoSelectionLabel.setText(_translate("MainWindow", "Numerical optimisation algo: "))
        self.configOptButton.setText(_translate("MainWindow", "Configure"))
        self.launchButton.setText(_translate("MainWindow", "Launch"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.setting_tab_widget.setTabText(self.setting_tab_widget.indexOf(self.setting_tab), _translate("MainWindow", "Tab 1"))
        self.setting_tab_widget.setTabText(self.setting_tab_widget.indexOf(self.correction_tab), _translate("MainWindow", "Tab 2"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.plotPane), _translate("MainWindow", "Tab 1"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.networkfityPane), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
