include:
  - project: acc-co/devops/python/acc-py-gitlab-ci-templates
    file: v2/python.gitlab-ci.yml

variables:
  project_name: "acc_app_optimisation"
  PY_VERSION: "3.7"
  ACC_PY_BASE_IMAGE_TAG: '2020.11'
  ACC_PY_BASE_IMAGE_NAME: 'acc-py_cc7_gui_ci'

build_wheel:
  extends: .acc_py_build_wheel

test_wheel:
  extends: .acc_py_wheel_test

publish:
  extends: .acc_py_publish
