# SPDX-FileCopyrightText: 2020-2023 CERN
# SPDX-FileCopyrightText: 2023 GSI Helmholtzzentrum für Schwerionenforschung
# SPDX-FileNotice: All rights not expressly granted are reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later OR EUPL-1.2+

include:
  - project: acc-co/devops/python/acc-py-gitlab-ci-templates
    file: v2/python.gitlab-ci.yml

variables:
  project_name: "acc_app_optimisation"
  PY_VERSION: "3.11"
  ACC_PY_BASE_IMAGE_TAG: '2023.06'


build_wheel:
  extends: .acc_py_build_wheel

test_pre-commit_py39:
  variables:
    PY_VERSION: "3.9"
  extends: .acc_py_pre-commit
  before_script:
    - !reference [.acc_py_pre-commit, before_script]
    - python -m pip install pylint .[test]

test_pre-commit_py311:
  variables:
    PY_VERSION: "3.11"
  extends: .acc_py_pre-commit
  before_script:
    - !reference [.acc_py_pre-commit, before_script]
    - python -m pip install pylint .[test]

#test_wheel_py37:
#  extends: .acc_py_wheel_test
#  script:
#    - mkdir -p ~/not-the-source-dir && cd ~/not-the-source-dir
#    - run_headless python -m pytest --pyargs ${project_name}

#test_wheel_py39:
#  extends: .acc_py_wheel_test
#  variables:
#    PY_VERSION: "3.9"
#    ACC_PY_BASE_IMAGE_TAG: '2021.12'
#  script:
#    - mkdir -p ~/not-the-source-dir && cd ~/not-the-source-dir
#    - run_headless python -m pytest --pyargs ${project_name}

test_wheel:
  extends: .acc_py_wheel_test
#  variables:
#    PY_VERSION: "3.11"
#    ACC_PY_BASE_IMAGE_TAG: '2023.06'
#  script:
#    - mkdir -p ~/not-the-source-dir && cd ~/not-the-source-dir
#    - run_headless python -m pytest --pyargs ${project_name}

publish:
  extends: .acc_py_publish
