# SPDX-FileCopyrightText: 2020-2023 CERN
# SPDX-FileCopyrightText: 2023 GSI Helmholtzzentrum für Schwerionenforschung
# SPDX-FileNotice: All rights not expressly granted are reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later OR EUPL-1.2+

include:
  - project: acc-co/devops/python/acc-py-gitlab-ci-templates
    file: v2/python.gitlab-ci.yml

variables:
  project_name: "acc_app_optimisation"
  PY_VERSION: "3.11"
  ACC_PY_BASE_IMAGE_TAG: '2023.06'


build_wheel:
  extends: .acc_py_build_wheel

test_pre-commit:
  extends:
    - .acc_py_pre-commit
    - .acc_py_run_on_acc_py
  before_script:
    - !reference [ .acc_py_run_on_acc_py, before_script ]
    - !reference [ .acc_py_pre-commit, before_script ]

test_wheel:
  extends: .acc_py_wheel_test
  variables:
    ACC_PY_BASE_IMAGE_NAME: "acc-py_el9_gui_ci"
  script:
    - mkdir -p ~/not-the-source-dir && cd ~/not-the-source-dir
    - run_headless python -m pytest --pyargs ${project_name}

publish:
  extends: .acc_py_publish
