# SPDX-FileCopyrightText: 2020-2023 CERN
# SPDX-FileCopyrightText: 2023 GSI Helmholtzzentrum für Schwerionenforschung
# SPDX-FileNotice: All rights not expressly granted are reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later OR EUPL-1.2+

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html and
# https://acc-py.docs.cern.ch/howto/use-pre-commit-with-acc-py/#available-pre-commit-hooks
# for more hooks

repos:

- repo: ssh://git@gitlab.cern.ch:7999/acc-co/devops/python/devtools/acc-py-deploy-pre-commit.git
  rev: v2.8.1
  hooks:
  - id: check-lockfiles

- repo: https://gitlab.cern.ch/pre-commit-hook-mirrors/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
    args: ["--unsafe"]
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://gitlab.cern.ch/pre-commit-hook-mirrors/astral-sh/ruff-pre-commit
  rev: v0.9.4
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://gitlab.cern.ch/pre-commit-hook-mirrors/fsfe/reuse-tool
  rev: v4.0.3
  hooks:
    - id: reuse

- repo: https://gitlab.cern.ch/pre-commit-hook-mirrors/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
  - id: mypy
    additional_dependencies:
    - PyQt5-stubs ~= 5.0
