[build-system]
requires = ["setuptools >= 40.8", "wheel >= 0.34"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
    | \.git
    | \.mypy_cache
    | build
    | dist
)/
'''

[tool.isort]
profile = "black"
