[build-system]
requires = [
    "setuptools >= 45",
    "wheel >= 0.36",
    "setuptools-scm[toml] >= 7.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.black]
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
    | \.git
    | \.mypy_cache
    | build
    | dist
)/
'''

[tool.isort]
profile = "black"

[tool.pylint.MAIN]
extension-pkg-allow-list = ['PyQt5']

[tool.pylint.REPORTS]
score = false
reports = false
output-format = 'colorized'

[tool.pylint.FORMAT]
ignore-long-lines = '<?https?://\S+>?$'

[tool.pylint.DESIGN]
max-attributes = 14

[tool.pylint.'MESSAGES CONTROL']
disable = [
    'duplicate-code',
    'fixme',
    'missing-module-docstring',
    'missing-class-docstring',
    'missing-function-docstring',
    'too-few-public-methods',
]
